// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package responses

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson39ae8b0dDecodeOtusNotificationAppApiResponses(in *jlexer.Lexer, out *EventSendOkResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "success":
			out.Success = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson39ae8b0dEncodeOtusNotificationAppApiResponses(out *jwriter.Writer, in EventSendOkResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Success))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EventSendOkResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson39ae8b0dEncodeOtusNotificationAppApiResponses(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventSendOkResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson39ae8b0dEncodeOtusNotificationAppApiResponses(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventSendOkResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson39ae8b0dDecodeOtusNotificationAppApiResponses(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventSendOkResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson39ae8b0dDecodeOtusNotificationAppApiResponses(l, v)
}
